### ISSUE TITLE
Cannot compile: One dependency is no longer available

### ISSUE THREAD

**Issue by skycommand** [douglasjunior/emage#13]
Hi. I tried to compile the app yesterday. `yarn` fails because this dependency is no longer available:

    "imagemin": "git+https://github.com/douglasjunior/imagemin.git#patch-1"

Any ideas as to what to do?

**Comment by douglasjunior** [comment]
Sorry, please try again.

**Comment by skycommand** [comment]
@douglasjunior Still no luck. The new error is as follows:

error Couldn't find match for "1bececa58b0b8bed696a800f8f1b9a478797da41" in "refs/heads/master,refs/heads/patch-1,refs/tags/0.1.0,refs/tags/0.1.1,refs/tags/0.1.2,refs/tags/0.1.3,refs/tags/0.2.0,refs/tags/0.2.1,refs/tags/0.2.2,refs/tags/0.2.3,refs/tags/0.3.0,refs/tags/0.4.0,refs/tags/0.4.1,refs/tags/0.4.2,refs/tags/0.4.3,refs/tags/0.4.4,refs/tags/0.4.5,refs/tags/0.4.6,refs/tags/5.0.0,refs/tags/5.0.1,refs/tags/5.0.2,refs/tags/5.1.0,refs/tags/5.1.1,refs/tags/5.1.2,refs/tags/v0.4.7,refs/tags/v0.4.8,refs/tags/v0.4.9,refs/tags/v1.0.0,refs/tags/v1.0.1,refs/tags/v1.0.2,refs/tags/v1.0.3,refs/tags/v1.0.4,refs/tags/v1.0.5,refs/tags/v2.0.0,refs/tags/v2.0.1,refs/tags/v2.1.0,refs/tags/v2.1.1,refs/tags/v2.1.2,refs/tags/v2.2.0,refs/tags/v2.2.1,refs/tags/v3.0.0,refs/tags/v3.1.0,refs/tags/v3.2.0,refs/tags/v3.2.1,refs/tags/v3.2.2,refs/tags/v4.0.0,refs/tags/v5.1.3,refs/tags/v5.2.0,refs/tags/v5.2.1,refs/tags/v5.2.2,refs/tags/v5.3.0,refs/tags/v5.3.1,refs/tags/v6.0.0,refs/tags/v6.1.0,refs/tags/v7.0.0,refs/tags/v7.0.1" for "https://github.com/douglasjunior/imagemin.git".

**Comment by douglasjunior** [comment]
Remove the yarn.lock and run install again.

**Comment by skycommand** [comment]
Much obliged. 😀

**Comment by douglasjunior** [comment]
I will update yarn.lock to avoid future problems, thanks for reporting!

**Comment by skycommand** [comment]
Oh. Looks like the change to my fork got a mention here. Sadly, my yarn.lock files are useless to you because I took a dependency on `node-sass@4.14.1` and `immutable@^3.7.4` (so that I can use Visual Studio 2019 and Python 3.8 instead of Visual Studio 2017 and Python 2.)

**Comment by douglasjunior** [comment]
Feel free to send a PR with updates.
