### ISSUE TITLE
E-Mage Dark Mode

### ISSUE THREAD

**Issue by jabcreations** [douglasjunior/emage#16]
![eyes-burning](https://github.com/user-attachments/assets/85534679-c4bf-485f-a367-f36a914e70f2)

Hi, can we please have support for dark mode?

**Comment by skycommand** [comment]
This project is dead.

- The last commit to this project was [5 years and 7 months ago](https://github.com/douglasjunior/emage/commits/master/). 
- This project has a backlog of open issues [dating back to 2018](https://github.com/douglasjunior/emage/issues).
- This project has [never accepted or merged a single pull request](https://github.com/douglasjunior/emage/pulls).

So, essentially, the maintainer neither develops it nor lets others contribute to it.

If you're looking for an alternative, try FileOptimizer. That's open-source too.

**Comment by jabcreations** [comment]
Eh.

I did look through the code, the problem is here:
https://github.com/douglasjunior/emage/blob/master/app/styles/default.scss

Though I don't compile software. The install has the files paked, great - apparently there are many different PAK file types.

Thank you for the suggestion; I tried it and it took seven frigin minutes to reduce a PNG by 24%,,,eh.

**Comment by douglasjunior** [comment]
Hey everyone,

I want to clarify that the project may seem quiet at the moment, but it's definitely not dead.

The question is that none of the previous contributions have been relevant enough, or the authors haven't provided the necessary time for me to review them. Unfortunately, working on this project is something I do in my free time, so it has to wait.

To make relevant changes, we need to address the outdated or deprecated project dependencies. Here's what needs to be done:

1. Update Electron and Webpack
2. Update imagemin
3. Update Ant Design
4. Ensure everything works and compiles with Node 22

Despite these challenges, the project is still functional for me, and I'll maintain it until we have some meaningful collaborations.
