### ISSUE TITLE
Calling from the command line

### ISSUE THREAD

**Issue by Inateno** [douglasjunior/emage#3]
Hey buddy,

I came up to your tool while crawling for a cross-platform solution (instead of ImageOptim).
Tried and... nice work, it's great and works nice.

I would like to know if there is a way to summon it with command line to integrate this tool in my build script? If no, I think that won't be "to hard" since it's an electron app.

Second point, I tried to do a pngquant optim first then using your tool and I've got something a little bit better (from 5.7KB to 5.62KB on my test, not that bad). Since PNGQUANT is cross-platform it would be a nice stuff to add!

Let me know if I can help with this.

Edit: I cloned the repo but I don't get how do you get imagemin (and the other) since it's not in the package.json?

Anyway, the pngquant exist as imagemin and is super simple to add (I did it, trying to make a build, but I'll directly try some code in my node env)

**Comment by douglasjunior** [comment]
I think that you are looking for the https://github.com/imagemin/imagemin

This was the library I used to integrate the algorithms into this tool.

**Comment by Inateno** [comment]
Yep, indeed.
The fact is your tool combine all of them and do "automatically" svg/gif/png/jpg.

I tried to add imagemin and all plugins (included pngquant) and got 5.63Kb, so not bad.

It would be preferable (and easier) to have a complete tool to rely on and simply call it with command line and arguments (also an other features you can include, possibility to tweak all arguments for each plugins), but I understand if it's not in your priorities ;)

**Comment by douglasjunior** [comment]
I have a very short time lately, but that's a good idea. 😀

**Comment by Inateno** [comment]
Nop, just watched, not as good as makng a script (I took part of your Process.js added in my build and works fine lol).

No worries I understand about time, same for me ;)
Just tell me how the imagemin is fetched in your project because I don't see it in the packages.json ??

If I ever manage to build the Electron-app I will do some PR ;)

**Comment by Inateno** [comment]
Ah yes missed this one! Cool.
Will give a try this w.e
