### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by skycommand** [douglasjunior/emage#7]
Hi. 😊 

To speed up optimizing a very large number of images, I ran this app on a server. The server did not have an Internet connection. That was when I noticed certain parts of the UI did not load in the absence of an Internet connection.

It appears certain assets are missing from the app, and are only loaded in the presence of an Internet connection.

**Comment by douglasjunior** [comment]
Hi, thanks for the feedback.

We use Ant Design to help to create interfaces, maybe we need to maintain some assets locally.

**Comment by skycommand** [comment]
Closing because the repo is dead

**Comment by douglasjunior** [comment]
The repository is not dead, I marked the issue as "enhancement". This means that anyone interested in implementing the suggestion can submit a PR at any time. I will be happy to review it.

**Comment by skycommand** [comment]
@douglasjunior Be honest with yourself; [you don't accept anyone's pull requests](https://github.com/douglasjunior/emage/commits/master). You once [encouraged me to open a PR](https://github.com/douglasjunior/emage/issues/13), but after I did, [you ignored it](https://github.com/douglasjunior/emage/pull/14). Furthermore, this repo hasn't had any changes in two years. It is dead.

I've moved on to another re-compression app. I closed this to clear my GitHub queue.
